experiment:
    experiment_id: 'experiment-test'
    environment: 'RockPaperScissors-v0'
    benchmarking_episodes: 5
    number_of_runs: 2
    self_play_training_schemes: ['fullhistoryselfplay', 'naiveselfplay', 'halfhistoryselfplay']
    algorithms: ['ppo']
    seed: 69

agents:
    ppo:
        discount: 0.99
        use_gae: False
        use_cuda: False
        gae_tau: 0.95
        entropy_weight: 0.01
        gradient_clip: 5
        optimization_epochs: 10
        mini_batch_size: 256
        ppo_ratio_clip: 0.2
        learning_rate: 3.0e-4
        adam_eps: 1.0e-5
        horizon: 128
        phi_arch: 'MLP'
        actor_arch: 'None'
        critic_arch: 'None'
